name: Build

run-name: Build ${{ github.ref_name }}

on:
  push:
    branches: [ main, develop, 1.4.x ]
  pull_request:
    branches: [ main, develop, 1.4.x ]
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:
  workflow_call:

concurrency:
  group: java-ngrok-singleton

jobs:
  init:
    name: Initialize test resources

    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
      NGROK_SUBDOMAIN: ${{ github.repository_owner }}

    runs-on: ubuntu-latest

    outputs:
      NGROK_PARENT_DOMAIN: ${{ steps.init.outputs.NGROK_PARENT_DOMAIN }}
      NGROK_DOMAIN: ${{ steps.init.outputs.NGROK_DOMAIN }}
      NGROK_TCP_EDGE_ADDR: ${{ steps.init.outputs.NGROK_TCP_EDGE_ADDR }}
      NGROK_TCP_EDGE_ID: ${{ steps.init.outputs.NGROK_TCP_EDGE_ID }}
      NGROK_HTTP_EDGE_DOMAIN: ${{ steps.init.outputs.NGROK_HTTP_EDGE_DOMAIN }}
      NGROK_HTTP_EDGE_ID: ${{ steps.init.outputs.NGROK_HTTP_EDGE_ID }}
      NGROK_TLS_EDGE_DOMAIN: ${{ steps.init.outputs.NGROK_TLS_EDGE_DOMAIN }}
      NGROK_TLS_EDGE_ID: ${{ steps.init.outputs.NGROK_TLS_EDGE_ID }}

    steps:
      - uses: actions/checkout@v4
      - name: Initialize test resources
        id: init
        run: make init-test-resources

  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml
    secrets: inherit

  build:
    name: Build
    needs: init

    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
      NGROK_PARENT_DOMAIN: ${{ needs.init.outputs.NGROK_PARENT_DOMAIN }}
      NGROK_DOMAIN: ${{ needs.init.outputs.NGROK_DOMAIN }}
      NGROK_TCP_EDGE_ADDR: ${{ needs.init.outputs.NGROK_TCP_EDGE_ADDR }}
      NGROK_TCP_EDGE_ID: ${{ needs.init.outputs.NGROK_TCP_EDGE_ID }}
      NGROK_HTTP_EDGE_DOMAIN: ${{ needs.init.outputs.NGROK_HTTP_EDGE_DOMAIN }}
      NGROK_HTTP_EDGE_ID: ${{ needs.init.outputs.NGROK_HTTP_EDGE_ID }}
      NGROK_TLS_EDGE_DOMAIN: ${{ needs.init.outputs.NGROK_TLS_EDGE_DOMAIN }}
      NGROK_TLS_EDGE_ID: ${{ needs.init.outputs.NGROK_TLS_EDGE_ID }}

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java-version: [ "21" ]
        include:
          - java-version: "11"
            os: ubuntu-latest
          - java-version: "15"
            os: ubuntu-latest
          - java-version: "17"
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: zulu
      - name: Build
        run: make build
      - name: Test
        run: make test

  cleanup:
    name: Cleanup test resources
    needs: [validate, build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cleanup test resources
        if: always()
        run: make prune-test-resources
